### ISSUE TITLE
Error localization does not work when logging in to account

### ISSUE THREAD

**Issue by MrAliev** [LazZiya/XLocalizer.Samples#1]
Error localization does not work when logging in to an account. 
For example, when entering an unregistered E-Mail or an incorrect password, error messages are always displayed in the default language.

**Comment by LazZiya** [comment]
Which sample project have you tried?
Meanwhile, these samples are using the free plan of [MyMemory Translate](https://mymemory.translated.net/doc/usagelimits.php) service, and it grants 1000 word only for the free plan. In case you need more follow the instructions in the sample home page or in the [docs](https://docs.ziyad.info/en/XLocalizer/v1.0/translate-services-mymemory.md) or pick another [supported translation service](https://docs.ziyad.info/en/XLocalizer/v1.0/translate-services.md).

**Comment by LazZiya** [comment]
additionally, the projects are not fully localized, I did only few pages for demonstration purpose, the rest of the page needs setup as described in [the docs.](https://docs.ziyad.info/en/XLocalizer/v1.0/localizing-views.md)

**Comment by MrAliev** [comment]
I used [XmlLocalizationSample](https://github.com/LazZiya/XLocalizer.Samples) 
My Memory - I registered an E-Mail and received 30,000 words, so I don't think that's the problem
Regarding the localization of errors, according to your documentation, everything is done correctly (or I'm missing something). When registering, it shows all errors according to the established locale, but when logging in, all errors are in English

**Comment by LazZiya** [comment]
Can you show a screenshot or share what you have done? I rechecked the sample, it worked fine! the only message in English was ["Invalid login attempt" in Login page,](https://github.com/LazZiya/XLocalizer.Samples/blob/387faceb7cff1670ac1e29ccc82f5856a973b298/XmlLocalizationSample/XmlLocalizationSample/Areas/Identity/Pages/Account/Login.cshtml.cs#L108), if this is the case, then fix is easy, just inject `IStringLocalizer` and modify it to be localized (amendment already provided)

As I mentioned in my second comment, I localized only few pages including (login and register) pages, the rest of identity pages needs to be scaffolded and modified to be localized.

**Comment by MrAliev** [comment]
Yes, that's right! I probably broke something while studying the project...
Now I downloaded the project again, added the IStringLocalizer, and everything worked as it should!  
Thank you for the great product, and for the prompt response! 👍
